### ISSUE TITLE
[QUESTION] Class users does not exist in .../.../IlluminateRegistry.php:330

### ISSUE THREAD

**Issue by appkr** [laravel-doctrine/orm#148]
I'm palying around with the QuickStart project. While testing, I got following error. Help me~
### Package version, Laravel version

Tested against two versions.
- Laravel Framework version 5.1.21 (LTS)
- Laravel Framework version 5.2.31
### Steps to reproduce the behaviour

``` http
POST /auth/register

name=Foo&email=foo@bar.com&password=password&password_confirmation=password
```

``` php
// app/Http/routes.php

// Authentication Test
Route::get('/', function() {
    return 'See you soon~';
});

Route::get('home', [
    'middleware' => 'auth',
    function() {
        return 'Welcome back, ' . Auth::user()->getName();
    }
]);

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');
```
### Stack Trace

``` sh
[2016-05-10 06:02:40] local.ERROR: ReflectionException: Class users does not exist in .../Laravel-Doctrine-Quickstart/vendor/laravel-doctrine/orm/src/IlluminateRegistry.php:330
Stack trace:
#0 .../Laravel-Doctrine-Quickstart/vendor/laravel-doctrine/orm/src/IlluminateRegistry.php(330): ReflectionClass->__construct('users')
#1 .../Laravel-Doctrine-Quickstart/vendor/laravel-doctrine/orm/src/Validation/DoctrinePresenceVerifier.php(112): LaravelDoctrine\ORM\IlluminateRegistry->getManagerForClass('users')
#2 .../Laravel-Doctrine-Quickstart/vendor/laravel-doctrine/orm/src/Validation/DoctrinePresenceVerifier.php(85): LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier->getEntityManager('users')
#3 .../Laravel-Doctrine-Quickstart/vendor/laravel-doctrine/orm/src/Validation/DoctrinePresenceVerifier.php(38): LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier->select('users')
#4 .../Laravel-Doctrine-Quickstart/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(1043): LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier->getCount('users', 'email', 'foo@bar.com', NULL, NULL, Array)
#5 .../Laravel-Doctrine-Quickstart/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(362): Illuminate\Validation\Validator->validateUnique('email', 'foo@bar.com', Array, Object(Illuminate\Validation\Validator))
#6 .../Laravel-Doctrine-Quickstart/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(314): Illuminate\Validation\Validator->validate('email', 'Unique')
#7 .../Laravel-Doctrine-Quickstart/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(335): Illuminate\Validation\Validator->passes()
#8 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(2424): Illuminate\Validation\Validator->fails()
#9 [internal function]: App\Http\Controllers\Auth\AuthController->postRegister(Object(Illuminate\Http\Request))
#10 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(8842): call_user_func_array(Array, Array)
#11 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(8911): Illuminate\Routing\Controller->callAction('postRegister', Array)
#12 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(8891): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), 'postRegister')
#13 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 .../Laravel-Doctrine-Quickstart/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(8892): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(8877): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postRegister')
#22 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(7831): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postRegister')
#23 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(7802): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#24 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(7455): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(7456): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(7444): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(7429): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(2304): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(2928): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#38 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(12881): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#41 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(11504): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#44 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(12622): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#47 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(12561): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#50 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(2978): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(2251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 .../Laravel-Doctrine-Quickstart/bootstrap/cache/compiled.php(2234): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57 .../Laravel-Doctrine-Quickstart/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58 .../Laravel-Doctrine-Quickstart/server.php(21): require_once('/Users/Juwon/wo...')
#59 {main}
```

**Comment by patrickbrouwers** [comment]
It seems the validator in `postRegister` refers to the table `users` rather than the entity `User::class`. Make sure in your unique/exists validation rules you refer to the FQN of the entity rather than the table name.

**Comment by appkr** [comment]
Yeah!! You are right~ You are my best friend. Tested at `laravel/laravel:5.2.31` and `laravel/framework:5.2.31`.

``` php
// app/Http/Controllers/Auth/AuthController.php

-use App\User;
+use App\Domain\Entities\User;
+use Doctrine\ORM\EntityManager;

     protected function validator(array $data)
     {
         return Validator::make($data, [
             'name' => 'required|max:255',
-            'email' => 'required|email|max:255|unique:users',
+            'email' => 'required|email|max:255|unique:App\Domain\Entities\User,email',
             'password' => 'required|min:6|confirmed',
         ]);
     }

     protected function create(array $data)
     {
-        return User::create([
-            'name' => $data['name'],
-            'email' => $data['email'],
-            'password' => bcrypt($data['password']),
-        ]);
+        $user = new User(
+            $data['name'],
+            $data['email'],
+            bcrypt($data['password'])
+        );
+
+        \EntityManager::persist($user);
+        \EntityManager::flush();
+
+        return $user;
     }
```

Testing password reset is my next itinerary. I'll post another question, if there is one. Hope you don't mind. Thanks for help!

**Comment by patrickbrouwers** [comment]
No problem, you can also join on Slack btw! http://slack.laraveldoctrine.org/

**Comment by appkr** [comment]
Thanks for inviting me to the Slack channel. I'll be there soon. 
One update is that password reset seems working with minor change.

``` php
// app/Http/Controllers/PasswordController

@@ -29,4 +29,21 @@ class PasswordController extends Controller
     {
         $this->middleware('guest');
     }
+
+    /**
+     * Reset the given user's password.
+     *
+     * @param  \Illuminate\Contracts\Auth\CanResetPassword  $user
+     * @param  string  $password
+     * @return void
+     */
+    protected function resetPassword($user, $password)
+    {
+        $user->setPassword(bcrypt($password));
+        $user->setRememberToken(str_random(60));
+        \EntityManager::persist($user);
+        \EntityManager::flush();
+
+        \Auth::guard($this->getGuard())->login($user);
+    }
 }
```
