### ISSUE TITLE
Unknown column type "carbondatetime" with "fluent" driver

### ISSUE THREAD

**Issue by appkr** [laravel-doctrine/orm#149]
Hi again? I got another problem.
### Package version, Laravel version

Laravel Framework 5.2.31
### Actual behaviour

``` sh
[2016-05-11 04:40:17] local.ERROR: Doctrine\DBAL\DBALException: Unknown column type "carbondatetime" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. in /home/vagrant/laravel-doctrine-db2/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:228
Stack trace:
#0 /home/vagrant/laravel-doctrine-db2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php(172): Doctrine\DBAL\DBALException::unknownColumnType('carbondatetime')
#1 /home/vagrant/laravel-doctrine-db2/vendor/laravel-doctrine/fluent/src/Builders/Field.php(96): Doctrine\DBAL\Types\Type::getType('carbondatetime')
#2 /home/vagrant/laravel-doctrine-db2/vendor/laravel-doctrine/fluent/src/Builders/Traits/Fields.php(16): LaravelDoctrine\Fluent\Builders\Field::make(Object(Doctrine\ORM\Mapping\Builder\ClassMetadataBuilder), 'carbondatetime', 'created_at')
#3 /home/vagrant/laravel-doctrine-db2/vendor/laravel-doctrine/fluent/src/Builders/Traits/Dates.php(46): LaravelDoctrine\Fluent\Builders\Builder->field('carbondatetime', 'created_at', NULL)
#4 /home/vagrant/laravel-doctrine-db2/vendor/laravel-doctrine/fluent/src/Builders/Traits/Dates.php(86): LaravelDoctrine\Fluent\Builders\Builder->carbonDateTime('created_at', NULL)
#5 /home/vagrant/laravel-doctrine-db2/app/Infrastructure/Mappings/Fluent/TaskMapping.php(32): LaravelDoctrine\Fluent\Builders\Builder->timestamp('created_at')
#6 /home/vagrant/laravel-doctrine-db2/vendor/laravel-doctrine/fluent/src/Mappers/AbstractMapper.php(31): App\Infrastructure\Mappings\Fluent\TaskMapping->map(Object(LaravelDoctrine\Fluent\Builders\Builder))
#7 /home/vagrant/laravel-doctrine-db2/vendor/laravel-doctrine/fluent/src/FluentDriver.php(50): LaravelDoctrine\Fluent\Mappers\AbstractMapper->map(Object(LaravelDoctrine\Fluent\Builders\Builder))
#8 /home/vagrant/laravel-doctrine-db2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(108): LaravelDoctrine\Fluent\FluentDriver->loadMetadataForClass('App\\Domain\\Enti...', Object(LaravelDoctrine\Fluent\Extensions\ExtensibleClassMetadata))
#9 /home/vagrant/laravel-doctrine-db2/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(151): Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain->loadMetadataForClass('App\\Domain\\Enti...', Object(LaravelDoctrine\Fluent\Extensions\ExtensibleClassMetadata))
#10 /home/vagrant/laravel-doctrine-db2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(LaravelDoctrine\Fluent\Extensions\ExtensibleClassMetadata), NULL, false, Array)
#11 /home/vagrant/laravel-doctrine-db2/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('App\\Domain\\Enti...')
#12 /home/vagrant/laravel-doctrine-db2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(216): Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata('App\\Domain\\Enti...')
#13 /home/vagrant/laravel-doctrine-db2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(115): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('App\\Domain\\Enti...')
#14 /home/vagrant/laravel-doctrine-db2/vendor/laravel-doctrine/orm/src/Console/SchemaCreateCommand.php(47): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata()
#15 [internal function]: LaravelDoctrine\ORM\Console\SchemaCreateCommand->fire(Object(LaravelDoctrine\ORM\IlluminateRegistry))
#16 /home/vagrant/laravel-doctrine-db2/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#17 /home/vagrant/laravel-doctrine-db2/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#18 /home/vagrant/laravel-doctrine-db2/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/laravel-doctrine-db2/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/laravel-doctrine-db2/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/laravel-doctrine-db2/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(LaravelDoctrine\ORM\Console\SchemaCreateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/laravel-doctrine-db2/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/laravel-doctrine-db2/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/vagrant/laravel-doctrine-db2/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}
```
### Steps to reproduce the behaviour
- No problem with `'meta' => 'annotations'` in doctrine.php
- Change the setting to `'meta' => 'fluent'` and add `'mapping_types' => ['carbondatetime' => 'datetime']`
- And then issue a command `$ php artisan doctrine:schema:create`

\* I did it against MySQL and IBM DB2. End results are the same.

Thanks.

**Comment by appkr** [comment]
Just forget it! I will not use fluent but stick to annotations. I just forgot my main mission: make DB2 work with Laravel. Annotations works good and that's fine to me. Sorry for annoying you.

**Comment by patrickbrouwers** [comment]
If you want to use Carbon, you need to enable the extension:

http://www.laraveldoctrine.org/docs/1.1/extensions/custom-functions

**Comment by appkr** [comment]
Thanks for the answer. I tried but was not successful. I would not go further for the fluent. 

Anyway I and my team are supposed to do a project for public sector for a couple of month. The customer's requirement is Laravel and DB2(why why why 😁). 

While searching the Internet, I met laravel-doctrine, seems that it is the only doable solution. Untill now I was studying the feasibility. I think I'll have to leave many questions on Slack, IF the project starts. Thanks in advance~

**Comment by patrickbrouwers** [comment]
I'm using `->timestamp()` myself in several projects with Fluent. If you enable Carbon extension or alternatively use `->dateTime()`, I'm sure it works just fine.

**Comment by appkr** [comment]
[EDIT] What is 'Carbon extension'? Where can I find and activate it?
[EDIT2] Solved! Now I like fluent.

Thanks friend. I'll try it again tomorrow. By the way do you prefer fluent over annotation? I don't like annotation either(not familiar with). Can I ask why?

**Comment by josenicomaia** [comment]
Sorry for the late answer. I guess that you are missusing `mapping_types` directive.
The key is the database type and the value is the doctrine type.

![image](https://cloud.githubusercontent.com/assets/1703754/16454593/b4da8718-3de7-11e6-9a90-d4569b1ef3d4.png)
http://doctrine-orm.readthedocs.io/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix

When doctrine reads the data from the database, it need to select an conversor for the database type using an doctrine type, that doctrine implements (or a custom one that you can create too).

So, in your case that you are trying to change the default datetime type, you should do this:

```
'mapping_types' => [
   'datetime' => 'carbondatetime'
]
```
