### ISSUE TITLE
[1.0] Container error when binding repositories

### ISSUE THREAD

**Issue by EwanValentine** [laravel-doctrine/orm#85]
Apologies, me again,

I keep getting:

```
[Illuminate\Contracts\Container\BindingResolutionException]
  Unresolvable dependency resolving [Parameter #0 [ <required> $em ]] in class Doctrine\ORM\Entity
  Repository
```

I'm binding my repo as followed within my service provider class

```
$this->app->bind(NodeRepository::class, function($app) {
            return new \SixtyFiveTwenty\Repositories\Node\NodeRepository(
                app('em'),
                new ClassMetadata('\SixtyFiveTwenty\Entities\Node\Node')
            );
});
```

**Comment by sisve** [comment]
I spent longer than I dare to admit trying to resolve `Doctrine\ORM\Entity` until I noticed the badly placed row-break; and it's `Doctrine\ORM\EntityRepository`. Could you show us a stack-trace for the exception, and the code that triggers the resolution (I'm guessing a call to Application::bind or Application::make)? Or any clarification when you get that error?

**Comment by patrickbrouwers** [comment]
Assuming `NodeRepository::class`  and `SixtyFiveTwenty\Repositories\Node\NodeRepository` are two different classes, are you sure you are resolving the right class?

**Comment by EwanValentine** [comment]
Hi folks,

The error was actually being triggered whenever I hit any artisan command. I narrowed it down to the fact I had:

``` php
/**
     * Create a new command instance.
     */
    public function __construct(NodeRepository $repository)
    {
        parent::__construct();

        $this->repository = $repository;
    }
```

In one of my commands. I think the container resolution of `NodeRepository` was causing the error. If I changed it to use `EntityManager::getRepository(Node::class);` that resolved it, but it's not _really_ a 'fix'.  

Full stack-trace:

```

[2015-11-04 11:14:23] development.ERROR: exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $em ]] in class Doctrine\ORM\EntityRepository' in /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php:824
Stack trace:
#0 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\Container\Container->resolveNonClass(Object(ReflectionParameter))
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(772): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(627): Illuminate\Container\Container->build('SixtyFiveTwenty...', Array)
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('SixtyFiveTwenty...', Array)
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(838): Illuminate\Foundation\Application->make('SixtyFiveTwenty...')
#5 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(801): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#6 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(772): Illuminate\Container\Container->getDependencies(Array, Array)
#7 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(627): Illuminate\Container\Container->build('SixtyFiveTwenty...', Array)
#8 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('SixtyFiveTwenty...', Array)
#9 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(109): Illuminate\Foundation\Application->make('SixtyFiveTwenty...')
#10 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(123): Illuminate\Console\Application->resolve('SixtyFiveTwenty...')
#11 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(226): Illuminate\Console\Application->resolveCommands(Array)
#12 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Illuminate\Foundation\Console\Kernel->getArtisan()
#13 /var/www/api/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}

```

Container binding in one of my service providers:

``` php
$this->app->bind(NodeRepository::class, function($app) {
            return new \SixtyFiveTwenty\Repositories\Node\NodeRepository(
                $app['em'],
                new ClassMetadata('\SixtyFiveTwenty\Entities\Node\Node')
            );
        });

```

Cheers again!

**Comment by patrickbrouwers** [comment]
Can you re-read my last message and tell me if I'm right?

**Comment by EwanValentine** [comment]
Yep! Sorry you're absolutely spot on. My bad! Thanks guys.
